COLORSCHEME = 'nord'
local vimo = vim.o

vimo.backspace = 'indent,eol,start'
vimo.backup = false
vimo.completeopt = 'menuone,noselect,noinsert'
vimo.cursorcolumn = ualse
vimo.cursorline = true
vimo.errorbells = false
vimo.expandtab = true
vimo.foldmethod = 'marker'
vimo.hidden = true
vimo.hlsearch = false
vimo.incsearch = true
vimo.joinspaces = false
vimo.lazyredraw = true
vimo.number = true
vimo.relativenumber = true
vimo.scrolloff = 15
vimo.shiftwidth = 4
vimo.shortmess = 'c'
vimo.signcolumn = 'yes'
vimo.smartcase = true
vimo.softtabstop = 4
vimo.splitbelow = true
vimo.splitright = true
vimo.swapfile = false
vimo.tabstop = 4
vimo.title = true
vimo.updatetime = 50
vimo.wrap = false
vimo.colorcolumn = vim.fn.join(vim.fn.range(80,999),",")
vimo.showtabline = 0
vimo.smartindent = true
vimo.termguicolors = true
-- vim.o.clipboard = 'unnamedplus'
